# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 807cb8faf0e71a669da9f9017210fb9e2cef10ee75102671ca4432dfc2d4b9260fe9046898861dcdece78bea676c3b76d533a49fcabe505dcd24e113184a7508

test:
  secret_key_base: 266c0497498442bf443c8e27b997ae5e305ebfc552917ded592e3b5c7c1f796c4bc7372cf1436c47c78ac6fce6977f73c8eead84fcf8e6a96c52366cdf4b2d80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
